### ISSUE TITLE
A Few More Files

### ISSUE THREAD

**Issue by stgarf** [kris-anderson/remove-zoom-macos#2]
```php
~/Library/Preferences/us.zoom.xos.Hotkey.plist  # Assuming custom/saved shortcuts
~/Library/Preferences/us.zoom.airhost.plist  # Assuming if you've airplayed
~/Library/Mobile Documents/iCloud~us~zoom~videomeetings  # Assuming could save things from meetings to iCloud
~/Library/Application Support/CloudDocs/session/containers/iCloud.us.zoom.videomeetings.plist
~/Library/Application Support/CloudDocs/session/containers/iCloud.us.zoom.videomeetings
/Library/Audio/Plug-Ins/HAL/ZoomAudioDevice.driver
```

Here's a few more files that Zoom leaves littered about.

Of particular note is `ZoomAudioDevice.driver` which creates another sounds interface on the system. <img width="230" alt="zoomaudiodevice" src="https://user-images.githubusercontent.com/1694002/79690613-157fb500-8210-11ea-8f8f-245009180408.png">

**Comment by kris-anderson** [comment]
Thank you for finding those and letting me know about them. I've updated the script with this PR: #3

**Comment by OceanEnigma** [comment]
Found these files after running the script and then [fzf](https://github.com/junegunn/fzf) to sweep ~/Library
```
~/Library/Receipts/us.zoom.pkg.videomeeting.bom
~/Library/Receipts/us.zoom.pkg.videomeeting.plist
```

@kris-anderson Thanks for your effort and that pretty script! very helpful and enjoyable to run :)

**Comment by kris-anderson** [comment]
Thank you for the feedback @OceanEnigma. I added those additional files, plus two more I found, in my latest merge:
https://github.com/kris-anderson/remove-zoom-macos/pull/8/commits/83aba8b725d61bce8a15a49dc5161b9d236548c9

I don't have a `~/Library/Receipts/` folder path myself, and the latest zoom installer isn't adding those files for me. Is there a chance you installed Zoom before 2020 when I first created this script and started tracking down Zoom cruft? I think it's worth adding any of the cruft Zoom has added over the years to the script, I was just curious why I haven't found those files yet myself.

**Comment by OceanEnigma** [comment]
Thanks for updating the repository! 

I found these files after installing [zoom desktop Apple silicon version](https://zoom.us/client/5.17.11.31580/zoomusInstallerFull.pkg?archType=arm64) on M2 mac with MacOs sonoma 14.x 

This might be specific to a certain platform or macOS version, but I'm not entirely sure. Hopefully this helps anyway!
